# Numpy arrays


In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(1)

array([1.])

In [14]:
np.ones((1,3))

array([[1., 1., 1.]])

In [15]:
np.linspace(0, 2, 10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(5)

array([0.10885841, 0.28350342, 0.47796521, 0.47374466, 0.88550935])

In [18]:
np.random.rand(5,2)

array([[0.19466534, 0.2359613 ],
       [0.44981074, 0.64494089],
       [0.06873057, 0.811494  ],
       [0.1269014 , 0.05737557],
       [0.4268837 , 0.95705001]])

In [19]:
np.random.randn(2) # random normal distribution, [-1 to 1]

array([ 0.82992378, -0.66988596])

In [23]:
np.random.randint(1, 100, 10) # 100 excluded

array([ 8, 23, 70, 10, 21, 39, 82, 10, 31, 18])

In [24]:
arr = np.arange(25)

In [25]:
ranarr = np.random.randint(0, 50, 10)

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr

array([ 3,  8, 18, 17, 29, 13, 19, 17, 13, 29])

In [28]:
ranarr.max(), ranarr.min()

(29, 3)

In [30]:
ranarr.argmax(), ranarr.argmin() # where is the max, where is the min

(4, 0)

In [35]:
ranarr.shape

(10,)

In [36]:
arr.dtype

dtype('int64')